# numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
arr= np.array([1,2,3,4,5])
arr
arr.ndim

1

In [7]:
arrzero=np.array(45)
arrzero
arrzero.ndim

0

In [8]:
arr3= np.array([1,2,3,4,5,6,7,8,9,10])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[1:6]

array([2, 3, 4, 5])

In [10]:
arr3[:5]

array([1, 2, 3, 4, 5])

In [11]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
arr2.size

10

In [15]:
arr4=arr2.copy()
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
np.zeros((4,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.full((4,4),55)

array([[55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55]])

In [21]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
a=np.random.randint(10,50,10)
a

array([25, 16, 43, 26, 31, 15, 22, 34, 12, 43])

In [25]:
arrm= np.array([10,20,30,40,50])
arrm+2

array([12, 22, 32, 42, 52])

In [26]:
arrm-5

array([ 5, 15, 25, 35, 45])

In [27]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [28]:
a1-a2

array([-5, -5, -5, -5, -5])

In [29]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [30]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
np.min(arr2)

1

In [32]:
np.max(arr2)

10

In [33]:
np.sum(arr2)

55

In [34]:
a1

array([1, 2, 3, 4, 5])

In [35]:
for x in a1:
    print(x)

1
2
3
4
5


In [37]:
for a in arr2:
    for b in a:
        print(b)

1
2
3
4
5
6
7
8
9
10


In [39]:
a=np.array([[[[3,4,5,]]]])
a

array([[[[3, 4, 5]]]])

In [40]:
a.ndim

4